"""Migração de schema e virada de sessão.

`CREATE TABLE IF NOT EXISTS` não altera tabela criada por uma versão
anterior, então um banco já publicado não ganharia as colunas novas: ele
continuaria sem `codigo_rastreio` e toda consulta quebraria.

Este arquivo mudou bastante na virada do SQLite pro Postgres. O que saiu
foram os testes que montavam um `cerebro.db` no schema antigo com `sqlite3`
e conferiam `PRAGMA table_info`: aquilo protegia o arquivo de quem já usava
o app, e esse arquivo não é mais o banco. O que ficou é o comportamento que
continua valendo em qualquer banco: coluna que falta é acrescentada, a
migração é idempotente, e linha gravada por uma versão antiga continua
funcionando.
"""

import pytest

from app import database, models, repositories, services
from app.database import get_connection, init_db
from tests.conftest import id_por_nome


def _colunas(tabela):
    conn = get_connection()
    nomes = {
        linha["column_name"]
        for linha in conn.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_name = %s",
            (tabela,),
        ).fetchall()
    }
    conn.close()
    return nomes


@pytest.fixture
def tabela_sem_as_colunas_novas():
    """Recria `pedidos` no formato anterior ao rastreio, com um pedido dentro.

    É o equivalente do banco de quem atualizou o código sem migrar: a tabela
    existe, mas sem `codigo_rastreio` nem `status_notificado`.
    """
    conn = get_connection()
    conn.execute("DROP TABLE pedidos")
    conn.execute(
        """
        CREATE TABLE pedidos (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sessao_id TEXT,
            produto_id INTEGER NOT NULL,
            produto_nome TEXT NOT NULL,
            quantidade INTEGER NOT NULL,
            valor_total DOUBLE PRECISION NOT NULL,
            endereco_entrega TEXT,
            status TEXT NOT NULL DEFAULT 'confirmado',
            data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            data_entrega_agendada TEXT
        )
        """
    )
    conn.execute(
        """
        INSERT INTO pedidos (id, produto_id, produto_nome, quantidade, valor_total,
                             endereco_entrega, status, data_criacao)
        VALUES (1, 1, 'Notebook Titan X15', 1, 4899.90, 'Rua Antiga, 1',
                'confirmado', '2020-01-01 10:00:00+00')
        """
    )
    # Id inserido à mão não avança a sequência da coluna IDENTITY, e o
    # próximo pedido nasceria com id 1 de novo. É o mesmo passo que o script
    # de migração dá no fim, e por isso ele está reproduzido aqui.
    conn.execute(
        "SELECT setval(pg_get_serial_sequence('pedidos','id'), (SELECT MAX(id) FROM pedidos))"
    )
    conn.commit()
    conn.close()
    yield
    # Devolve o schema pro formato atual, senão o próximo teste herda a
    # tabela capenga: ela é criada uma vez por execução, não por caso.
    init_db()


def _migrar_e_adotar():
    """Roda o que o app roda ao abrir: migra o schema e adota o que estava
    gravado antes das sessões existirem."""
    from app import sessao
    from app.database import adotar_dados_orfaos

    init_db()
    adotar_dados_orfaos(sessao.atual())


def test_tabela_antiga_nao_tem_as_colunas_novas(tabela_sem_as_colunas_novas):
    colunas = _colunas("pedidos")
    assert "codigo_rastreio" not in colunas
    assert "status_notificado" not in colunas


def test_init_db_acrescenta_as_colunas_que_faltam(tabela_sem_as_colunas_novas):
    init_db()
    assert {"codigo_rastreio", "status_notificado"} <= _colunas("pedidos")


def test_migracao_preserva_os_dados(tabela_sem_as_colunas_novas):
    _migrar_e_adotar()
    pedido = repositories.obter_pedido(1)
    assert pedido["produto_nome"] == "Notebook Titan X15"
    assert pedido["endereco_entrega"] == "Rua Antiga, 1"
    assert pedido["codigo_rastreio"] is None


def test_migracao_repetida_nao_mexe_nos_dados(tabela_sem_as_colunas_novas):
    """ALTER TABLE repetido sem `IF NOT EXISTS` estouraria com "column already
    exists" e deixaria a transação abortada."""
    for _ in range(3):
        _migrar_e_adotar()

    pedidos = repositories.listar_pedidos()
    assert len(pedidos) == 1
    assert pedidos[0]["produto_nome"] == "Notebook Titan X15"


def test_migrar_colunas_ignora_tabela_que_nao_existe():
    """`to_regclass` volta nulo pra tabela ausente, e o ALTER nela estouraria."""
    conn = get_connection()
    conn.execute("DROP TABLE messages")
    try:
        database._migrar_colunas(conn)
    finally:
        conn.close()
        init_db()


def test_pedido_antigo_continua_funcionando(tabela_sem_as_colunas_novas):
    _migrar_e_adotar()
    pedido = services.obter_pedido(1)
    assert pedido["codigo_rastreio"] == services.gerar_codigo_rastreio(1)
    assert pedido["status"] == "entregue"

    rastreio = services.rastrear_pedido(1)
    assert rastreio["etapa_atual"] == "entregue"
    assert rastreio["codigo_rastreio"] == pedido["codigo_rastreio"]


def test_pedido_antigo_e_notificado_uma_vez_so(tabela_sem_as_colunas_novas):
    """Linha migrada tem `status_notificado` nulo: nada foi comunicado ainda,
    então vale um aviso do estado atual, e só um."""
    _migrar_e_adotar()
    novas = services.sincronizar_notificacoes()
    assert len(novas) == 1
    assert "entregue" in novas[0]["content"]
    assert services.sincronizar_notificacoes() == []


def test_pedido_novo_em_banco_migrado(tabela_sem_as_colunas_novas):
    """Migrar precisa deixar o banco pronto pra escrita também: o INSERT de
    pedido preenche `status_notificado`, coluna que não existia antes."""
    _migrar_e_adotar()
    pedido = services.criar_pedido(id_por_nome("Air Fryer 4L Digital"))

    assert pedido["codigo_rastreio"] == services.gerar_codigo_rastreio(pedido["id"])
    assert repositories.obter_pedido(pedido["id"])["status_notificado"] == "confirmado"

    novas = services.sincronizar_notificacoes()
    assert [f"#{pedido['id']}" in n["content"] for n in novas] == [False]


def test_status_gravado_por_versao_antiga_nao_vaza_pro_rastreio(
    tabela_sem_as_colunas_novas,
):
    """A versão anterior escrevia "entrega agendada" na coluna status, valor
    que nem existe em ETAPAS_RASTREIO, e o rastreio devolvia isso ao cliente."""
    conn = get_connection()
    conn.execute("UPDATE pedidos SET status = 'entrega agendada' WHERE id = 1")
    conn.commit()
    conn.close()

    _migrar_e_adotar()
    assert services.obter_pedido(1)["status"] in models.ETAPAS_RASTREIO
    assert services.rastrear_pedido(1)["etapa_atual"] in models.ETAPAS_RASTREIO
    assert services.rastrear_pedido(1)["localizacao"] != "Desconhecida"


def test_banco_novo_ja_nasce_com_as_colunas():
    init_db()
    assert {"codigo_rastreio", "status_notificado"} <= _colunas("pedidos")


def test_perfil_orfao_e_aceito_pelo_schema():
    """`sessao_id` NULL precisa caber na tabela pra que a adoção exista.

    No SQLite isso vinha de graça, porque ele aceita NULL em coluna de chave
    primária. No Postgres a chave virou UNIQUE NULLS NOT DISTINCT justamente
    pra continuar aceitando, e este teste é o que segura essa decisão.
    """
    conn = get_connection()
    conn.execute(
        "INSERT INTO perfil (sessao_id, chave, valor) VALUES (NULL, 'nome', 'Matheus')"
    )
    conn.commit()
    conn.close()

    from app import sessao

    database.adotar_dados_orfaos(sessao.atual())
    assert repositories.obter_perfil()["nome"] == "Matheus"


def test_perfil_orfao_repetido_nao_duplica():
    """NULLS NOT DISTINCT: sem ele, duas linhas órfãs com a mesma chave
    entrariam e o cadastro adotado ficaria dobrado."""
    conn = get_connection()
    conn.execute(
        "INSERT INTO perfil (sessao_id, chave, valor) VALUES (NULL, 'nome', 'Matheus')"
    )
    conn.commit()
    with pytest.raises(Exception):
        conn.execute(
            "INSERT INTO perfil (sessao_id, chave, valor) VALUES (NULL, 'nome', 'Outro')"
        )
    conn.close()


# --- Virada pra identidade por telefone ------------------------------------

def _como(sessao_id, funcao):
    """Roda algo como se a requisição fosse daquela sessão."""
    from app import sessao

    token = sessao.definir(sessao_id)
    try:
        return funcao()
    finally:
        sessao.restaurar(token)


def test_transferir_sessao_leva_conversa_pedido_e_cadastro():
    from app.database import transferir_sessao

    _como("cookie-antigo", lambda: repositories.inserir_mensagem("user", "oi"))
    _como("cookie-antigo", lambda: repositories.salvar_perfil("nome", "Matheus"))

    assert transferir_sessao("cookie-antigo", "5511988881234") is True

    assert _como("5511988881234", repositories.listar_mensagens)[0]["content"] == "oi"
    assert _como("5511988881234", repositories.obter_perfil)["nome"] == "Matheus"
    assert _como("cookie-antigo", repositories.listar_mensagens) == []


def test_transferir_sessao_nao_mescla_com_numero_que_ja_tem_dado():
    """Mesclar dois cadastros seria pior que não migrar, e não dá pra
    desfazer: o número que já conversou fica intocado."""
    from app.database import transferir_sessao

    _como("cookie-antigo", lambda: repositories.inserir_mensagem("user", "do cookie"))
    _como("5511988881234", lambda: repositories.inserir_mensagem("user", "do número"))

    assert transferir_sessao("cookie-antigo", "5511988881234") is False

    conversa = _como("5511988881234", repositories.listar_mensagens)
    assert [m["content"] for m in conversa] == ["do número"]


def test_transferir_sessao_de_origem_vazia_nao_faz_nada():
    from app.database import transferir_sessao

    assert transferir_sessao("cookie-antigo", "5511988881234") is False
