"""Modelo de dados: schema das tabelas e constantes de domínio.

O projeto usa PostgreSQL com SQL puro (sem ORM), então este arquivo guarda o
DDL das tabelas em vez de classes de ORM.

Três decisões do DDL que não são óbvias na tradução que veio do SQLite:

- **`GENERATED BY DEFAULT AS IDENTITY`, não `ALWAYS`.** "BY DEFAULT" deixa
  inserir o id explicitamente, que é o que a migração do `cerebro.db`
  precisou fazer pra preservar o número do pedido que o cliente já viu no
  chat. Com `ALWAYS` aquele INSERT seria recusado.
- **Data é `TIMESTAMPTZ`, não texto.** O SQLite guardava string de
  `CURRENT_TIMESTAMP`, e o app inteiro lê `data_criacao` como string. Quem
  converte é `repositories._linha`, na fronteira, pra que o banco tenha tipo
  de verdade sem espalhar `datetime` por services, schemas e testes.
- **`perfil` usa UNIQUE, não PRIMARY KEY.** O SQLite aceita NULL em coluna
  de chave primária (é uma peculiaridade dele), e a linha órfã, de antes das
  sessões existirem, depende disso. O Postgres impõe NOT NULL em toda PK,
  então a restrição virou `UNIQUE NULLS NOT DISTINCT`, que aceita o NULL e
  ainda serve de alvo pro `ON CONFLICT` do upsert de cadastro.

Importa `whatsapp` porque os avisos de pedido são templates do canal, não
frases livres. A direção da dependência é essa e não a inversa: `whatsapp`
não conhece pedido, produto nem banco.
"""

from app import whatsapp

# `tipo` separa o que a Lu respondeu de um aviso automático de pedido. Os
# dois são role "assistant", porque ambos foram ditos por ela e o modelo
# precisa saber que avisou. Sem essa coluna, a única forma de distinguir na
# tela era casar o texto por regex, que quebra calado se a frase mudar.
TIPO_CHAT = "chat"
TIPO_NOTIFICACAO = "notificacao"

CREATE_MESSAGES = """
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id TEXT,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    tipo TEXT NOT NULL DEFAULT 'chat',
    -- JSONB em vez de texto com JSON dentro: o driver devolve a lista de ids
    -- pronta, o que dispensa o json.loads que existia na leitura.
    produtos JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
"""

CREATE_PEDIDOS = """
CREATE TABLE IF NOT EXISTS pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id TEXT,
    produto_id INTEGER NOT NULL,
    produto_nome TEXT NOT NULL,
    quantidade INTEGER NOT NULL,
    -- DOUBLE PRECISION, não NUMERIC: NUMERIC volta como Decimal e o valor
    -- entra em conta de float e em JSON de resposta sem conversão.
    valor_total DOUBLE PRECISION NOT NULL,
    endereco_entrega TEXT,
    status TEXT NOT NULL DEFAULT 'confirmado',
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Continua texto de propósito: é a data combinada com o cliente
    -- ("2026-09-15"), não instante. Vira DATE e o fuso do Brasil passa a
    -- exibir um dia antes, que é o bug que a regra do frontend já evita.
    data_entrega_agendada TEXT,
    codigo_rastreio TEXT,
    status_notificado TEXT
)
"""

# O índice do RAG. Os documentos continuam sendo código (`data/conhecimento.py`
# é a fonte da verdade), esta tabela é só o vetor já calculado: sem ela, todo
# boot reencodava o corpus inteiro antes da primeira busca.
CREATE_CONHECIMENTO_VETORES = """
CREATE TABLE IF NOT EXISTS conhecimento_vetores (
    documento_id INTEGER PRIMARY KEY,
    -- Impressão do texto indexado. É o que denuncia corpus editado: se o
    -- hash mudou, o vetor guardado é de outro texto e precisa ser refeito.
    impressao TEXT NOT NULL,
    vetor VECTOR({dimensoes}) NOT NULL
)
"""

# Cadastro do cliente. Nome e endereço não podem depender do rolar da
# conversa: a janela de histórico enviada ao modelo é limitada, então o que
# ficou pra trás some. Dado que se repete em todo pedido é cadastro, não
# mensagem.
CREATE_PERFIL = """
CREATE TABLE IF NOT EXISTS perfil (
    -- Aceita NULL de propósito: linha migrada de antes das sessões nasce
    -- órfã e é adotada no primeiro acesso, igual a mensagem e pedido.
    sessao_id TEXT,
    chave TEXT NOT NULL,
    valor TEXT NOT NULL,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- NULLS NOT DISTINCT (Postgres 15+) é o que permite manter o NULL acima:
    -- chave primária no Postgres seria NOT NULL na marra. Sem o "NOT
    -- DISTINCT", duas linhas órfãs com a mesma chave escapariam do upsert.
    UNIQUE NULLS NOT DISTINCT (sessao_id, chave)
)
"""

# O que o cliente revelou nesta conversa e que a janela de histórico faria
# sumir. É irmã de `perfil`, com a mesma forma, mas separada de propósito:
# nome e endereço são cadastro, valem daqui a seis meses; orçamento, recusa e
# finalidade valem pra esta compra. Misturar as duas faria a Lu tratar o
# "meu limite é 2 mil" de março como verdade em setembro.
CREATE_MEMORIA = """
CREATE TABLE IF NOT EXISTS memoria (
    sessao_id TEXT,
    chave TEXT NOT NULL,
    valor TEXT NOT NULL,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE NULLS NOT DISTINCT (sessao_id, chave)
)
"""

# Nota que o cliente deu ao atendimento. Fica separada de `eventos` porque é
# o único sinal que o cliente declarou de propósito: todo o resto é inferido,
# e misturar declaração com inferência faria o diagnóstico tratar palpite como
# fato.
CREATE_SATISFACAO = """
CREATE TABLE IF NOT EXISTS satisfacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id TEXT,
    nota SMALLINT NOT NULL,
    comentario TEXT,
    -- Sobre o que ele estava falando quando avaliou. Sem isso a nota é um
    -- número solto e não aponta pra nada que dê pra consertar.
    assunto TEXT,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
"""

# O que o sistema observou sozinho, e que vira matéria-prima do diagnóstico.
# Uma tabela só com `tipo` em vez de uma por sinal: são todos "aconteceu isto,
# nesta conversa, nesta hora", e o que muda é só o detalhe, que vai em JSONB.
CREATE_EVENTOS = """
CREATE TABLE IF NOT EXISTS eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id TEXT,
    tipo TEXT NOT NULL,
    detalhe JSONB,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
"""

# Cupom emitido. Guarda o valor **já calculado**, e não o percentual: o preço
# do produto muda com o tempo, e um cupom precisa valer o que foi prometido
# na hora em que foi prometido.
CREATE_CUPONS = """
CREATE TABLE IF NOT EXISTS cupons (
    codigo TEXT PRIMARY KEY,
    sessao_id TEXT,
    produto_id INTEGER NOT NULL,
    valor_desconto DOUBLE PRECISION NOT NULL,
    -- Guardado pra auditoria: permite conferir depois se algum cupom passou
    -- do teto, sem depender de recalcular com a margem de hoje.
    margem_na_emissao DOUBLE PRECISION NOT NULL,
    motivo TEXT,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expira_em TIMESTAMPTZ NOT NULL,
    usado_em TIMESTAMPTZ
)
"""

TABELAS = (
    CREATE_MESSAGES,
    CREATE_PEDIDOS,
    CREATE_PERFIL,
    CREATE_MEMORIA,
    CREATE_SATISFACAO,
    CREATE_EVENTOS,
    CREATE_CUPONS,
)

# Os sinais que o sistema observa sozinho. São os nomes usados em `eventos`,
# e cada um responde uma pergunta de melhoria diferente.
EVENTO_RAG_SEM_RESPOSTA = "rag_sem_resposta"      # o que a base não sabe
EVENTO_ABANDONO = "abandono"                      # onde a conversa morre
EVENTO_CUPOM_OFERECIDO = "cupom_oferecido"        # quanto custou tentar
EVENTO_CUPOM_USADO = "cupom_usado"                # se a tentativa converteu
EVENTO_FERRAMENTA_FALHOU = "ferramenta_falhou"    # onde o sistema quebra
EVENTO_PRODUTO_RECUSADO = "produto_recusado"      # o que o catálogo erra

# Nota de 1 a 5. Na tela do WhatsApp isso vira no máximo 3 botões de resposta
# (limite da Meta), então a coleta por botão usa os extremos e o meio.
NOTA_MINIMA = 1
NOTA_MAXIMA = 5

CAMPOS_PERFIL = ("nome", "endereco")

# O que a Lu anota da conversa. São três porque o quarto item que ela precisa
# lembrar, o que já sugeriu, não se anota: sai da coluna `messages.produtos`,
# que já guarda os ids citados. Dado que dá pra derivar não deve depender de
# o modelo lembrar de gravar.
CAMPOS_MEMORIA = ("orcamento", "recusou", "proposito")

# Como cada anotação aparece no prompt. O rótulo é escrito pro modelo ler,
# não é nome de coluna.
ROTULOS_MEMORIA = {
    "orcamento": "quanto ele quer gastar",
    "recusou": "o que ele já descartou",
    "proposito": "pra quem ou pra quê é a compra",
}

# Colunas acrescentadas depois que a tabela já existia. `CREATE TABLE IF NOT
# EXISTS` não altera tabela criada por uma versão anterior, então quem abre
# um banco antigo precisa de ALTER TABLE. Formato: tabela -> (coluna, tipo).
COLUNAS_ADICIONADAS = {
    "pedidos": (
        ("codigo_rastreio", "TEXT"),
        ("status_notificado", "TEXT"),
        ("sessao_id", "TEXT"),
    ),
    "messages": (
        ("tipo", "TEXT NOT NULL DEFAULT 'chat'"),
        # Ids dos produtos citados. Sem isso o cartão do produto só existe no
        # envio ao vivo e some quando a página recarrega.
        ("produtos", "JSONB"),
        ("sessao_id", "TEXT"),
    ),
}

# A reconstrução da tabela `perfil` saiu daqui junto com o SQLite: ela
# existia porque SQLite não altera chave primária com ALTER TABLE, e a
# solução era criar tabela nova, copiar e trocar, conferindo a contagem antes
# do DROP. No Postgres a mudança de restrição é um ALTER TABLE comum, e o
# `perfil` do banco novo já nasce com a chave certa.

STATUS_INICIAL = "confirmado"

# O status é sempre uma destas etapas. Agendamento de entrega não é status:
# mora em `data_entrega_agendada`, porque um pedido agendado continua
# andando pela logística (é separado, enviado, entregue).
ETAPAS_RASTREIO = [
    "confirmado",
    "em separação",
    "enviado",
    "saiu para entrega",
    "entregue",
]

LOCALIZACOES_MOCK = {
    "confirmado": "Centro de distribuição, Louveira/SP",
    "em separação": "Centro de distribuição, Louveira/SP",
    "enviado": "Centro de triagem, em trânsito",
    "saiu para entrega": "Unidade de entrega local",
    "entregue": "Endereço do cliente",
}

# Código de rastreio no formato dos Correios: 2 letras + 8 dígitos de série
# + 1 dígito verificador + "BR". O DV é calculado de verdade (módulo 11),
# mas a série é derivada do id do pedido: é rastreio mockado, não existe
# objeto postado do outro lado.
PREFIXO_RASTREIO = "LU"
SUFIXO_RASTREIO = "BR"
PESOS_DV_RASTREIO = (8, 6, 4, 2, 3, 5, 9, 7)

# Usado quando o pedido aponta pra um produto que saiu do catálogo mockado.
PRAZO_ENTREGA_PADRAO_DIAS = 7

# O que a Lu manda quando um pedido avança de etapa.
#
# São **templates da Cloud API**, não frases soltas, e o motivo é do canal:
# o aviso sai sozinho, às vezes dias depois da última mensagem do cliente, ou
# seja, fora da janela de 24 horas. Fora dela o WhatsApp só entrega template
# aprovado antes. Se um dia isto voltar a ser f-string, o aviso passa a ser
# recusado pela Meta em vez de chegar ao cliente.
#
# Todos são UTILITY: seguem uma ação do cliente (a compra) e não vendem
# nada. Acrescentar "aproveite" ou link de vitrine faria a Meta
# reclassificar como MARKETING, que custa mais caro e exige opt-in.
#
# O código de rastreio só aparece de "enviado" em diante, antes disso não há
# o que rastrear.
TEMPLATES_NOTIFICACAO = {
    "confirmado": whatsapp.Template(
        nome="pedido_confirmado",
        corpo="Seu pedido #{{1}} ({{2}}) foi confirmado e já entrou na fila de separação.",
        parametros=["id", "produto"],
        exemplo=["1042", "Air Fryer 4L Digital"],
    ),
    "em separação": whatsapp.Template(
        nome="pedido_em_separacao",
        corpo="Seu pedido #{{1}} ({{2}}) está em separação no centro de distribuição.",
        parametros=["id", "produto"],
        exemplo=["1042", "Air Fryer 4L Digital"],
    ),
    "enviado": whatsapp.Template(
        nome="pedido_enviado",
        corpo="Seu pedido #{{1}} ({{2}}) foi enviado. Código de rastreio: {{3}}",
        parametros=["id", "produto", "codigo"],
        exemplo=["1042", "Air Fryer 4L Digital", "LU000010426BR"],
    ),
    "saiu para entrega": whatsapp.Template(
        nome="pedido_saiu_para_entrega",
        corpo=(
            "Seu pedido #{{1}} ({{2}}) saiu para entrega e chega hoje. "
            "Código de rastreio: {{3}}"
        ),
        parametros=["id", "produto", "codigo"],
        exemplo=["1042", "Air Fryer 4L Digital", "LU000010426BR"],
    ),
    "entregue": whatsapp.Template(
        nome="pedido_entregue",
        corpo="Seu pedido #{{1}} ({{2}}) foi entregue. Qualquer coisa, é só me chamar.",
        parametros=["id", "produto"],
        exemplo=["1042", "Air Fryer 4L Digital"],
    ),
}

# Usado quando o pedido cai numa etapa sem template próprio. Não é template
# de verdade de propósito: etapa nova precisa de template novo aprovado, e
# esta frase existe só pra que a tela não fique muda enquanto isso.
TEMPLATE_GENERICO = "Seu pedido #{id} ({produto}) mudou de status: {status}."

# O cupom de recuperação. **MARKETING, não UTILITY**, e isso não é escolha:
# ele oferece desconto, o que é promocional por definição. Declarar UTILITY
# faria a Meta reclassificar sozinha (automático desde abril de 2025), e a
# reclassificação vem com cobrança maior e exigência de opt-in.
#
# Ele sai depois de dias de silêncio, ou seja, sempre fora da janela de 24
# horas, então template é a única forma de ele chegar ao cliente.
TEMPLATE_CUPOM = whatsapp.Template(
    nome="cupom_recuperacao",
    corpo=(
        "Oi {{1}}, vi que você ficou na dúvida sobre o {{2}}. "
        "Consegui um desconto de R$ {{3}} pra você: use o código {{4}} "
        "até {{5}} e ele sai por R$ {{6}}."
    ),
    parametros=["nome", "produto", "desconto", "codigo", "validade", "preco_final"],
    categoria=whatsapp.CATEGORIA_MARKETING,
    exemplo=["Matheus", "Air Fryer 4L Digital", "45,00", "LUX7K2M", "16/08", "404,00"],
)

CRITERIOS_SUGESTAO = (
    "melhor_preco",
    "melhor_prazo",
    "melhor_avaliacao",
    "melhor_custo_beneficio",
)
