"""Leva o conteúdo de um `cerebro.db` antigo pro Postgres.

Roda uma vez por ambiente que já tinha o SQLite:

    python -m scripts.migrar_sqlite_para_postgres            # usa ./cerebro.db
    python -m scripts.migrar_sqlite_para_postgres outro.db

Quatro cuidados que este script existe pra não errar:

- **O id do pedido é preservado.** O cliente já viu "pedido #2" no chat, e a
  mensagem antiga no histórico cita esse número. Deixar o Postgres gerar id
  novo faria a conversa apontar pra pedido que não existe. É por isso que a
  coluna é `GENERATED BY DEFAULT AS IDENTITY`, e não `ALWAYS`.
- **Quem já está no destino sai da frente, não atropela.** Se o app rodou
  contra o Postgres antes da migração, ele gravou linhas com id 1, 2, 3, os
  mesmos do SQLite. A primeira versão deste script resolvia com
  `ON CONFLICT DO NOTHING`, e o resultado foi silencioso e errado: as duas
  primeiras mensagens do histórico antigo foram descartadas, e a contagem
  final bateu por coincidência. Agora as linhas do destino são renumeradas
  pro fim antes de qualquer INSERT, e nenhum dos dois lados se perde.
- **A data vai marcada como UTC.** O SQLite gravava `CURRENT_TIMESTAMP` em
  UTC, sem fuso na string. Jogar essa string crua numa coluna TIMESTAMPTZ
  faz o Postgres assumir o fuso da sessão e deslocar tudo em três horas, o
  que envelheceria os pedidos e pularia etapas do rastreio.
- **A conferência é `destino == origem + o que já havia`.** Comparar só o
  total contra a origem foi o que deixou o erro acima passar batido.
"""

import json
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from psycopg.types.json import Jsonb

from app.database import get_connection, init_db

FORMATOS = ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M", "%Y-%m-%d")

TABELAS = ("messages", "pedidos", "perfil")


def _data(valor: Optional[str]) -> Optional[datetime]:
    """String do SQLite pra datetime ciente de que aquilo era UTC."""
    if not valor:
        return None
    texto = str(valor).strip().replace("T", " ").split(".")[0]
    for formato in FORMATOS:
        try:
            return datetime.strptime(texto, formato).replace(tzinfo=timezone.utc)
        except ValueError:
            continue
    return None


def _colunas(conn: sqlite3.Connection, tabela: str) -> set:
    return {linha[1] for linha in conn.execute(f"PRAGMA table_info({tabela})")}


def _valor(linha: sqlite3.Row, coluna: str, colunas: set):
    """Lê a coluna se o banco antigo a tiver. Versões diferentes do schema
    circularam, e um `cerebro.db` antigo pode não ter `sessao_id`."""
    return linha[coluna] if coluna in colunas else None


def _abrir_espaco(origem: sqlite3.Connection, destino, tabela: str) -> None:
    """Renumera pro fim as linhas que o destino já tinha na faixa da origem.

    Sem isto, id repetido faz o INSERT ser descartado e o histórico antigo
    volta furado. O deslocamento é o maior id dos dois lados, então o destino
    dos remanejados fica acima de tudo que existe e nenhum id colide durante
    o próprio UPDATE.
    """
    maior_origem = origem.execute(f"SELECT MAX(id) FROM {tabela}").fetchone()[0] or 0
    maior_destino = destino.execute(
        f"SELECT COALESCE(MAX(id), 0) AS m FROM {tabela}"
    ).fetchone()["m"]
    if not maior_origem or not maior_destino:
        return

    deslocamento = max(maior_origem, maior_destino)
    cursor = destino.execute(
        f"UPDATE {tabela} SET id = id + %s WHERE id <= %s",
        (deslocamento, maior_origem),
    )
    if cursor.rowcount:
        print(f"  {tabela}: {cursor.rowcount} linhas do destino remanejadas pro fim")


def migrar(caminho: Path) -> None:
    if not caminho.exists():
        print(f"Nada a migrar: {caminho} não existe.")
        return

    origem = sqlite3.connect(caminho)
    origem.row_factory = sqlite3.Row

    init_db()
    destino = get_connection()

    previo = {}
    for tabela in TABELAS:
        previo[tabela] = destino.execute(
            f"SELECT COUNT(*) AS c FROM {tabela}"
        ).fetchone()["c"]
        if previo[tabela]:
            print(f"  {tabela}: já tinha {previo[tabela]} linhas no Postgres")

    for tabela in ("messages", "pedidos"):
        _abrir_espaco(origem, destino, tabela)

    colunas_msg = _colunas(origem, "messages")
    for linha in origem.execute("SELECT * FROM messages ORDER BY id"):
        produtos = _valor(linha, "produtos", colunas_msg)
        destino.execute(
            """
            INSERT INTO messages (id, sessao_id, role, content, tipo, produtos, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            """,
            (
                linha["id"],
                _valor(linha, "sessao_id", colunas_msg),
                linha["role"],
                linha["content"],
                _valor(linha, "tipo", colunas_msg) or "chat",
                Jsonb(json.loads(produtos)) if produtos else None,
                _data(_valor(linha, "created_at", colunas_msg)),
            ),
        )

    colunas_ped = _colunas(origem, "pedidos")
    for linha in origem.execute("SELECT * FROM pedidos ORDER BY id"):
        destino.execute(
            """
            INSERT INTO pedidos (
                id, sessao_id, produto_id, produto_nome, quantidade, valor_total,
                endereco_entrega, status, data_criacao, data_entrega_agendada,
                codigo_rastreio, status_notificado
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                linha["id"],
                _valor(linha, "sessao_id", colunas_ped),
                linha["produto_id"],
                linha["produto_nome"],
                linha["quantidade"],
                linha["valor_total"],
                _valor(linha, "endereco_entrega", colunas_ped),
                linha["status"],
                _data(linha["data_criacao"]),
                _valor(linha, "data_entrega_agendada", colunas_ped),
                _valor(linha, "codigo_rastreio", colunas_ped),
                _valor(linha, "status_notificado", colunas_ped),
            ),
        )

    colunas_perfil = _colunas(origem, "perfil")
    if colunas_perfil:
        for linha in origem.execute("SELECT * FROM perfil"):
            destino.execute(
                """
                INSERT INTO perfil (sessao_id, chave, valor, atualizado_em)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (sessao_id, chave) DO NOTHING
                """,
                (
                    _valor(linha, "sessao_id", colunas_perfil),
                    linha["chave"],
                    linha["valor"],
                    _data(_valor(linha, "atualizado_em", colunas_perfil)) or datetime.now(timezone.utc),
                ),
            )

    # Sem isto, o próximo pedido nasceria com id 1 e colidiria com o migrado:
    # a sequência da coluna IDENTITY não sabe dos ids inseridos à mão.
    for tabela in ("messages", "pedidos"):
        destino.execute(
            f"""
            SELECT setval(
                pg_get_serial_sequence('{tabela}', 'id'),
                COALESCE((SELECT MAX(id) FROM {tabela}), 1),
                (SELECT COUNT(*) FROM {tabela}) > 0
            )
            """
        )

    destino.commit()

    print("Conferência (origem + o que já havia = destino):")
    ok = True
    for tabela in TABELAS:
        try:
            antes = origem.execute(f"SELECT COUNT(*) FROM {tabela}").fetchone()[0]
        except sqlite3.OperationalError:
            antes = 0
        depois = destino.execute(f"SELECT COUNT(*) AS c FROM {tabela}").fetchone()["c"]
        esperado = antes + previo[tabela]
        marca = "ok" if depois == esperado else "DIVERGIU"
        ok = ok and depois == esperado
        print(f"  {tabela}: {antes} + {previo[tabela]} = {esperado}, tem {depois} ({marca})")

    destino.close()
    origem.close()

    if not ok:
        raise SystemExit("Migração incompleta: o SQLite original não foi tocado.")
    print(f"\nPronto. O {caminho} continua no lugar, como backup.")


if __name__ == "__main__":
    alvo = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("cerebro.db")
    migrar(alvo)
